# Generated by Django 5.2.13 on 2026-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
